### ISSUE TITLE
Do not untag images

### ISSUE THREAD

**Issue by discordianfish** [docker-infra/docker-proper#1]
Right now docker-proper tries to remove all images create a given time ago. Docker won't remove them if they are in use but it will untag them.

**Comment by xbglowx** [comment]
Should be fixed by https://github.com/docker-infra/docker-proper/commit/bd021f03d0c5918d600a65765239a4aed4894f57

**Comment by xbglowx** [comment]
FYI, starting with docker 1.13 gc of containers and images will be a built-in.
